motor_micro_node:
  ros__parameters:
    motor_directions:
    - 1
    - 1
    - 1
    - 0
    - 1
    - 0
    - 1
    - 1
    motor_mappings:
    - 8
    - 6
    - 7
    - 2
    - 3
    - 1
    - 4
    - 5
